//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgDev.IDE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgDev.IDE.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersionFormat {
            get {
                return ResourceManager.GetString("AboutVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid identifier (alphanumeric and underscore, starting with a letter)..
        /// </summary>
        internal static string ErrorExpectedIdentifier {
            get {
                return ResourceManager.GetString("ErrorExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string FileTypeClass {
            get {
                return ResourceManager.GetString("FileTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        internal static string FileTypeDataType {
            get {
                return ResourceManager.GetString("FileTypeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string FileTypeFunction {
            get {
                return ResourceManager.GetString("FileTypeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function block.
        /// </summary>
        internal static string FileTypeFunctionBlock {
            get {
                return ResourceManager.GetString("FileTypeFunctionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables.
        /// </summary>
        internal static string FileTypeGlobalVars {
            get {
                return ResourceManager.GetString("FileTypeGlobalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string FileTypeInterface {
            get {
                return ResourceManager.GetString("FileTypeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string FileTypeProgram {
            get {
                return ResourceManager.GetString("FileTypeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Block Diagram (FBD).
        /// </summary>
        internal static string LanguageFBD {
            get {
                return ResourceManager.GetString("LanguageFBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction List (IL).
        /// </summary>
        internal static string LanguageIL {
            get {
                return ResourceManager.GetString("LanguageIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder Diagram (LD).
        /// </summary>
        internal static string LanguageLD {
            get {
                return ResourceManager.GetString("LanguageLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Function Chart (SFC).
        /// </summary>
        internal static string LanguageSFC {
            get {
                return ResourceManager.GetString("LanguageSFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Text (ST).
        /// </summary>
        internal static string LanguageST {
            get {
                return ResourceManager.GetString("LanguageST", resourceCulture);
            }
        }
    }
}
