//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgDev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgDev.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersionFormat {
            get {
                return ResourceManager.GetString("AboutVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - OSPA ProgDev.
        /// </summary>
        public static string AppFormTitle {
            get {
                return ResourceManager.GetString("AppFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string ButtonDontSave {
            get {
                return ResourceManager.GetString("ButtonDontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add file.
        /// </summary>
        public static string CommandAddFile {
            get {
                return ResourceManager.GetString("CommandAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid folder name: A-Z 0-9 _ , . - ( ).
        /// </summary>
        public static string ErrorExpectedFolder {
            get {
                return ResourceManager.GetString("ErrorExpectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid identifier (alphanumeric and underscore, starting with a letter)..
        /// </summary>
        public static string ErrorExpectedIdentifier {
            get {
                return ResourceManager.GetString("ErrorExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must either be blank or one or more identifiers separated by periods..
        /// </summary>
        public static string ErrorExpectedNamespaceOrEmpty {
            get {
                return ResourceManager.GetString("ErrorExpectedNamespaceOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle files must be contained in a folder..
        /// </summary>
        public static string ErrorFileAtRoot {
            get {
                return ResourceManager.GetString("ErrorFileAtRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A POU named &quot;{0}&quot; already exists in the folder &quot;{1}&quot;..
        /// </summary>
        public static string ErrorFileExists {
            get {
                return ResourceManager.GetString("ErrorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid POU language file extension..
        /// </summary>
        public static string ErrorInvalidLanguageExtension {
            get {
                return ResourceManager.GetString("ErrorInvalidLanguageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invald PouLanguage value..
        /// </summary>
        public static string ErrorInvalidPouLanguage {
            get {
                return ResourceManager.GetString("ErrorInvalidPouLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PouType value..
        /// </summary>
        public static string ErrorInvalidPouType {
            get {
                return ResourceManager.GetString("ErrorInvalidPouType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid POU type file extension..
        /// </summary>
        public static string ErrorInvalidTypeExtension {
            get {
                return ResourceManager.GetString("ErrorInvalidTypeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid combination of type and language..
        /// </summary>
        public static string ErrorInvalidTypeLanguageCombo {
            get {
                return ResourceManager.GetString("ErrorInvalidTypeLanguageCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed filename..
        /// </summary>
        public static string ErrorMalformedFilename {
            get {
                return ResourceManager.GetString("ErrorMalformedFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem opening the project..
        /// </summary>
        public static string ErrorOpenProject {
            get {
                return ResourceManager.GetString("ErrorOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string FileTypeClass {
            get {
                return ResourceManager.GetString("FileTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        public static string FileTypeDataType {
            get {
                return ResourceManager.GetString("FileTypeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string FileTypeFunction {
            get {
                return ResourceManager.GetString("FileTypeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function block.
        /// </summary>
        public static string FileTypeFunctionBlock {
            get {
                return ResourceManager.GetString("FileTypeFunctionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables.
        /// </summary>
        public static string FileTypeGlobalVars {
            get {
                return ResourceManager.GetString("FileTypeGlobalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string FileTypeInterface {
            get {
                return ResourceManager.GetString("FileTypeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string FileTypeProgram {
            get {
                return ResourceManager.GetString("FileTypeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Block Diagram (FBD).
        /// </summary>
        public static string LanguageFBD {
            get {
                return ResourceManager.GetString("LanguageFBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction List (IL).
        /// </summary>
        public static string LanguageIL {
            get {
                return ResourceManager.GetString("LanguageIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder Diagram (LD).
        /// </summary>
        public static string LanguageLD {
            get {
                return ResourceManager.GetString("LanguageLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Function Chart (SFC).
        /// </summary>
        public static string LanguageSFC {
            get {
                return ResourceManager.GetString("LanguageSFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Text (ST).
        /// </summary>
        public static string LanguageST {
            get {
                return ResourceManager.GetString("LanguageST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSPA ProgDev projects (*.{0})|*.{0}.
        /// </summary>
        public static string OpenProjectFilter {
            get {
                return ResourceManager.GetString("OpenProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string OpenProjectTitle {
            get {
                return ResourceManager.GetString("OpenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to {0}?.
        /// </summary>
        public static string SaveChangedPrompt {
            get {
                return ResourceManager.GetString("SaveChangedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string SaveProjectTitle {
            get {
                return ResourceManager.GetString("SaveProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ShortFileTypeClass {
            get {
                return ResourceManager.GetString("ShortFileTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        public static string ShortFileTypeDataType {
            get {
                return ResourceManager.GetString("ShortFileTypeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string ShortFileTypeFunction {
            get {
                return ResourceManager.GetString("ShortFileTypeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func. block.
        /// </summary>
        public static string ShortFileTypeFunctionBlock {
            get {
                return ResourceManager.GetString("ShortFileTypeFunctionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global vars.
        /// </summary>
        public static string ShortFileTypeGlobalVars {
            get {
                return ResourceManager.GetString("ShortFileTypeGlobalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string ShortFileTypeInterface {
            get {
                return ResourceManager.GetString("ShortFileTypeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string ShortFileTypeProgram {
            get {
                return ResourceManager.GetString("ShortFileTypeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBD.
        /// </summary>
        public static string ShortLanguageFBD {
            get {
                return ResourceManager.GetString("ShortLanguageFBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL.
        /// </summary>
        public static string ShortLanguageIL {
            get {
                return ResourceManager.GetString("ShortLanguageIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LD.
        /// </summary>
        public static string ShortLanguageLD {
            get {
                return ResourceManager.GetString("ShortLanguageLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFC.
        /// </summary>
        public static string ShortLanguageSFC {
            get {
                return ResourceManager.GetString("ShortLanguageSFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        public static string ShortLanguageST {
            get {
                return ResourceManager.GetString("ShortLanguageST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
    }
}
