// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef FeUserInterface_h
#define FeUserInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Table.H>

class ProgramWindow {
public:
  ProgramWindow();
  Fl_Double_Window *FlWindow;
  Fl_Menu_Bar *MenuBar;
  static Fl_Menu_Item menu_MenuBar[];
  static Fl_Menu_Item *FileMnu;
  static Fl_Menu_Item *NewProgramMnu;
  static Fl_Menu_Item *OpenProgramMnu;
  static Fl_Menu_Item *SaveProgramMnu;
  static Fl_Menu_Item *ExitMnu;
  static Fl_Menu_Item *EditMnu;
  static Fl_Menu_Item *ProgramMnu;
  static Fl_Menu_Item *ToolsMnu;
  static Fl_Menu_Item *HelpMnu;
  static Fl_Menu_Item *AboutMnu;
  Fl_Group *TasksGrp;
  Fl_Group *SymbolsGrp;
  Fl_Group *ObjectsGrp;
  Fl_Group *TemplatesGrp;
};
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>

class AboutWindow {
public:
  AboutWindow();
  Fl_Double_Window *FlWindow;
  Fl_Return_Button *CloseBtn;
};
#endif
