// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef FeUserInterface_h
#define FeUserInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Table.H>

class FeProgramWindow {
public:
  FeProgramWindow();
  Fl_Double_Window *FlWindow;
  Fl_Menu_Bar *MenuBar;
  static Fl_Menu_Item menu_MenuBar[];
  static Fl_Menu_Item *FileMnu;
  static Fl_Menu_Item *NewProgramMnu;
  static Fl_Menu_Item *OpenProgramMnu;
  static Fl_Menu_Item *SaveProgramMnu;
  static Fl_Menu_Item *ExitMnu;
  static Fl_Menu_Item *EditMnu;
  static Fl_Menu_Item *NewTaskMnu;
  static Fl_Menu_Item *NewObjectMnu;
  static Fl_Menu_Item *NewTemplateMnu;
  static Fl_Menu_Item *OpenItemMnu;
  static Fl_Menu_Item *DeleteItemMnu;
  static Fl_Menu_Item *ProgramMnu;
  static Fl_Menu_Item *ToolsMnu;
  static Fl_Menu_Item *HelpMnu;
  static Fl_Menu_Item *AboutMnu;
  Fl_Tabs *Tabs;
  Fl_Group *TasksGrp;
  Fl_Group *ObjectsGrp;
  Fl_Group *TemplatesGrp;
  Fl_Group *SymbolsGrp;
  Fl_Group *LibrariesGrp;
};
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>

class FeAboutWindow {
public:
  FeAboutWindow();
  Fl_Double_Window *FlWindow;
  Fl_Return_Button *CloseBtn;
};
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>

class FeTaskPropertiesWindow {
public:
  FeTaskPropertiesWindow();
  Fl_Double_Window *FlWindow;
  Fl_Input *NameTxt;
  Fl_Choice *ActivationCmb;
  Fl_Value_Input *IntervalTxt;
  Fl_Group *MillisecondsLbl;
  Fl_Choice *LanguageCmb;
  Fl_Return_Button *OkBtn;
  Fl_Button *CancelBtn;
};
#endif
