// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "FeUserInterface.h"

Fl_Menu_Item ProgramWindow::menu_MenuBar[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 12, 0},
 {"&New program ", 0x4006e,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"&Open program ", 0x4006f,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"&Save program ", 0x40073,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"E&xit ", 0x8ffc1,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 12, 0},
 {"New &task ", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"New &object ", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"New te&mplate ", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"O&pen item ", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"&Delete item... ", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Program", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Tools", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 12, 0},
 {"&About OSPASOFT ", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* ProgramWindow::FileMnu = ProgramWindow::menu_MenuBar + 0;
Fl_Menu_Item* ProgramWindow::NewProgramMnu = ProgramWindow::menu_MenuBar + 1;
Fl_Menu_Item* ProgramWindow::OpenProgramMnu = ProgramWindow::menu_MenuBar + 2;
Fl_Menu_Item* ProgramWindow::SaveProgramMnu = ProgramWindow::menu_MenuBar + 3;
Fl_Menu_Item* ProgramWindow::ExitMnu = ProgramWindow::menu_MenuBar + 4;
Fl_Menu_Item* ProgramWindow::EditMnu = ProgramWindow::menu_MenuBar + 6;
Fl_Menu_Item* ProgramWindow::NewTaskMnu = ProgramWindow::menu_MenuBar + 7;
Fl_Menu_Item* ProgramWindow::NewObjectMnu = ProgramWindow::menu_MenuBar + 8;
Fl_Menu_Item* ProgramWindow::NewTemplateMnu = ProgramWindow::menu_MenuBar + 9;
Fl_Menu_Item* ProgramWindow::OpenItemMnu = ProgramWindow::menu_MenuBar + 10;
Fl_Menu_Item* ProgramWindow::DeleteItemMnu = ProgramWindow::menu_MenuBar + 11;
Fl_Menu_Item* ProgramWindow::ProgramMnu = ProgramWindow::menu_MenuBar + 13;
Fl_Menu_Item* ProgramWindow::ToolsMnu = ProgramWindow::menu_MenuBar + 15;
Fl_Menu_Item* ProgramWindow::HelpMnu = ProgramWindow::menu_MenuBar + 17;
Fl_Menu_Item* ProgramWindow::AboutMnu = ProgramWindow::menu_MenuBar + 18;

ProgramWindow::ProgramWindow() {
  { FlWindow = new Fl_Double_Window(394, 410, "Program - OSPASOFT");
    FlWindow->labelsize(13);
    FlWindow->user_data((void*)(this));
    FlWindow->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Group* o = new Fl_Group(0, 30, 394, 371);
      o->labelsize(12);
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    { MenuBar = new Fl_Menu_Bar(0, 0, 394, 23);
      MenuBar->box(FL_THIN_UP_BOX);
      MenuBar->labelsize(12);
      MenuBar->textsize(11);
      MenuBar->menu(menu_MenuBar);
    } // Fl_Menu_Bar* MenuBar
    { Tabs = new Fl_Tabs(0, 23, 394, 384);
      Tabs->labelsize(12);
      { TasksGrp = new Fl_Group(0, 23, 394, 356, "T&asks");
        TasksGrp->labelsize(12);
        { Fl_Table* o = new Fl_Table(0, 23, 393, 355);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->labelfont(4);
          o->end();
          Fl_Group::current()->resizable(o);
        } // Fl_Table* o
        TasksGrp->end();
      } // Fl_Group* TasksGrp
      { ObjectsGrp = new Fl_Group(0, 25, 394, 350, "&Objects");
        ObjectsGrp->labelsize(12);
        ObjectsGrp->hide();
        ObjectsGrp->end();
      } // Fl_Group* ObjectsGrp
      { TemplatesGrp = new Fl_Group(0, 25, 394, 350, "Te&mplates");
        TemplatesGrp->labelsize(12);
        TemplatesGrp->hide();
        TemplatesGrp->end();
      } // Fl_Group* TemplatesGrp
      { SymbolsGrp = new Fl_Group(0, 25, 394, 350, "&Symbols");
        SymbolsGrp->labelsize(12);
        SymbolsGrp->hide();
        SymbolsGrp->end();
      } // Fl_Group* SymbolsGrp
      { LibrariesGrp = new Fl_Group(0, 25, 394, 350, "&Libraries");
        LibrariesGrp->labelsize(12);
        LibrariesGrp->hide();
        LibrariesGrp->end();
        Fl_Group::current()->resizable(LibrariesGrp);
      } // Fl_Group* LibrariesGrp
      Tabs->end();
    } // Fl_Tabs* Tabs
    FlWindow->size_range(325, 200);
    FlWindow->end();
  } // Fl_Double_Window* FlWindow
}

AboutWindow::AboutWindow() {
  { FlWindow = new Fl_Double_Window(405, 190, "About OSPASOFT");
    FlWindow->user_data((void*)(this));
    FlWindow->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Text_Display* o = new Fl_Text_Display(-2, 15, 15, 25, "OSPASOFT");
      o->box(FL_NO_BOX);
      o->labelfont(1);
      o->labelsize(24);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(-1, 40, 15, 25, "Programming software for the Open Source PLC Architecture");
      o->box(FL_NO_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { Fl_Text_Display* o = new Fl_Text_Display(-1, 70, 15, 25, "Copyright \302\251 2014 Brian Luft");
      o->box(FL_NO_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { CloseBtn = new Fl_Return_Button(310, 155, 85, 25, "Close");
      CloseBtn->labelsize(12);
    } // Fl_Return_Button* CloseBtn
    { Fl_Text_Display* o = new Fl_Text_Display(-1, 108, 15, 25, "OSPASOFT is based in part on the work of the FLTK project (http://www.fltk.or\
g).");
      o->box(FL_NO_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->align(Fl_Align(136));
    } // Fl_Text_Display* o
    FlWindow->set_modal();
    FlWindow->end();
  } // Fl_Double_Window* FlWindow
}

TaskPropertiesWindow::TaskPropertiesWindow() {
  { FlWindow = new Fl_Double_Window(376, 181, "Task Properties");
    FlWindow->user_data((void*)(this));
    { NameTxt = new Fl_Input(125, 10, 242, 25, "Task name: ");
      NameTxt->labelsize(12);
      NameTxt->textfont(4);
      NameTxt->textsize(12);
    } // Fl_Input* NameTxt
    { ActivationCmb = new Fl_Choice(125, 40, 140, 25, "Activation: ");
      ActivationCmb->down_box(FL_BORDER_BOX);
      ActivationCmb->labelsize(12);
      ActivationCmb->textsize(12);
    } // Fl_Choice* ActivationCmb
    { IntervalTxt = new Fl_Value_Input(125, 70, 60, 25, "Interval: ");
      IntervalTxt->labelsize(12);
      IntervalTxt->textfont(4);
      IntervalTxt->textsize(12);
    } // Fl_Value_Input* IntervalTxt
    { MillisecondsLbl = new Fl_Group(212, 70, 25, 25, "ms");
      MillisecondsLbl->labelsize(12);
      MillisecondsLbl->align(Fl_Align(FL_ALIGN_LEFT));
      MillisecondsLbl->end();
    } // Fl_Group* MillisecondsLbl
    { LanguageCmb = new Fl_Choice(125, 100, 140, 25, "Language: ");
      LanguageCmb->down_box(FL_BORDER_BOX);
      LanguageCmb->labelsize(12);
      LanguageCmb->textsize(12);
    } // Fl_Choice* LanguageCmb
    { OkBtn = new Fl_Return_Button(211, 145, 75, 25, "OK");
      OkBtn->labelsize(12);
    } // Fl_Return_Button* OkBtn
    { CancelBtn = new Fl_Button(291, 145, 75, 25, "Cancel");
      CancelBtn->labelsize(12);
    } // Fl_Button* CancelBtn
    FlWindow->set_modal();
    FlWindow->end();
  } // Fl_Double_Window* FlWindow
}
