//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgDev.FrontEnd {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppForm_SavedPositionExists {
            get {
                return ((bool)(this["AppForm_SavedPositionExists"]));
            }
            set {
                this["AppForm_SavedPositionExists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point AppForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["AppForm_Location"]));
            }
            set {
                this["AppForm_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Size AppForm_Size {
            get {
                return ((global::System.Drawing.Size)(this["AppForm_Size"]));
            }
            set {
                this["AppForm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState AppForm_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["AppForm_WindowState"]));
            }
            set {
                this["AppForm_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockLeft")]
        public global::WeifenLuo.WinFormsUI.Docking.DockState ProjectContentForm_DockState {
            get {
                return ((global::WeifenLuo.WinFormsUI.Docking.DockState)(this["ProjectContentForm_DockState"]));
            }
            set {
                this["ProjectContentForm_DockState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DockPanel_DockLeftPortion {
            get {
                return ((double)(this["DockPanel_DockLeftPortion"]));
            }
            set {
                this["DockPanel_DockLeftPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DockPanel_DockRightPortion {
            get {
                return ((double)(this["DockPanel_DockRightPortion"]));
            }
            set {
                this["DockPanel_DockRightPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DockPanel_DockTopPortion {
            get {
                return ((double)(this["DockPanel_DockTopPortion"]));
            }
            set {
                this["DockPanel_DockTopPortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DockPanel_DockBottomPortion {
            get {
                return ((double)(this["DockPanel_DockBottomPortion"]));
            }
            set {
                this["DockPanel_DockBottomPortion"] = value;
            }
        }
    }
}
