CC=g++
CFLAGS=-std=c++0x -Wall -Wunused -Wno-format-y2k -fno-exceptions -fno-strict-aliasing -I./include -I./lib/fltk/include -mwindows -DWIN32 -DUSE_OPENGL32  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
LDFLAGS=-L./lib/fltk/lib-mingw32 -lfltk -lole32 -luuid -lcomctl32 -mwindows -static-libgcc -static-libstdc++
EXECUTABLE=bin/ospasoft.exe
export

all:
	make -f Makefile.base

run:
	./$(EXECUTABLE) &
