CC=clang++
CFLAGS=-std=c++0x -Wall -Wunused -Wno-format-y2k -fno-exceptions -fno-strict-aliasing -I./include -I./lib/fltk/include -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
LDFLAGS=-L./lib/fltk/lib-mac
EXECUTABLE=bin/ospasoft
export

all:
	make -f Makefile.base
