CC=g++
CFLAGS=-std=c++0x -Wall -Wunused -Wno-format-y2k -fno-exceptions -fno-strict-aliasing -I./include `fltk-config --cxxflags` -DUSE_OPENGL32 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
LDFLAGS=`fltk-config --ldflags` -static-libgcc -static-libstdc++
EXECUTABLE=bin/ospasoft
export

all:
	make -f Makefile.base

run:
	./$(EXECUTABLE) &
